version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
  precise:
    format: '%(asctime)s [%(levelname)s] [%(threadName)s] [%(filename)s : %(lineno)d] %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class : logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: precise
    filename: /opt/logs/redismon.log
    when: 'D'
    interval: 1
    backupCount: 15
loggers:
  file_logger:
    level: INFO
    handlers: [file_handler]
    propagate: no
root:
  level: INFO
  handlers: [file_handler]